### PR TITLE
🛠Added Calculator command

### PR DESCRIPTION
**Pull request by dword64**
npm i discord-math

I added the Calculator command to it pretty simple.

### CODE REVIEW

**Comment by KSJaay** [comment]
I'm gonna remove calculator because that's already a command. I will update the readme list to make sure all the commands which have already been created are ticked off.

**Review by KSJaay — CHANGES_REQUESTED** [review]
Can you remove this

**Comment by dword64** [comment]
aight removed calc. what about the Twitch checker?

**Comment by KSJaay** [comment]
The twitch checker is nice, I might clean up the embed a bit. Thanks :)

**Pull request merged**
